# NGINX configuration
# Accepts HTTPS traffic and forwards PHP requests to WordPress php-fpm.

server {
	# Listen only on HTTPS port 443
	listen 443 ssl;

	# Domain required by the subject
	server_name tbolsako.42.fr;

	# WordPress files are mounted from the wordpress_data volume
	root /var/www/html;

	# Default index files
	index index.php index.html index.htm;

	# TLS configuration
	# Self-signed certificate generated in the Dockerfile
	ssl_certificate		/etc/nginx/ssl/inception.crt;
	ssl_certificate_key	/etc/nginx/ssl/inception.key;

	# The subject requires TLSv1.2 or TLSv1.3 only
	ssl_protocols TLSv1.2 TLSv1.3;

	# Main WordPress routing
	# Try to serve th requested file or directory.
	# If it doesn't exist, forward the request to index.php
	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	# PHP handling
	# NGINX doesn't execute PHP
	# It forwards PHP requests to php-fpm in the WordPress container
	location ~ \.php& {
		include snippets/fastcgi-php.conf;

		# "wordpress" is the Docker Compose service name
		# Docker DNS resolves it to the WordPress container IP
		fastcgi_pass wordpress:9000;
	}
}
