; PHP-FPM pool configuration

[www]

; Run PHP-FPM worker processes as www-data
user = www-data
group = www-data

; NGINX is in another container, so PHP-FPM must listen on TCP
listen = 0.0.0.0:9000

; Allow any container from the Docker network to connect
listen.allowed_clients = 0.0.0.0/0

; Basic process manager configuration
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Send logs to Docker
catch_workers_output = yes
